# Ejercicios - Práctica 7b: Tuberías y filtros. Subshells.

In [1]:
#VII.41
#VII.40
#VII.39
#VII.38
#VII.37
#VII.36
#VII.35
#VII.34
#VII.33
#VII.32
#VII.31
#VII.30
#VII.29
#VII.28
#VII.27
#VII.26
#VII.25
#VII.24
#VII.23
#VII.22
#VII.20
#VII.19
#VII.18
#VII.12
#VII.9
#VII.8
#VII.7
#VII.6
#VII.5
#VII.3
rm -rf ~/p7b-ejercicios
mkdir -p ~/p7b-ejercicios
cd ~/p7b-ejercicios

Clonando en 'zsh'...
remote: Enumerating objects: 103125, done.        
remote: Counting objects: 100% (3720/3720), done.        
remote: Compressing objects: 100% (1217/1217), done.        
remote: Total 103125 (delta 2641), reused 3272 (delta 2500), pack-reused 99405 (from 1)        
Recibiendo objetos: 100% (103125/103125), 36.15 MiB | 1.02 MiB/s, listo.
Resolviendo deltas: 100% (79425/79425), listo.


In [3]:
cd zsh && git checkout d8a3bff && cd .. 

Nota: cambiando a 'd8a3bff'.

Te encuentras en estado 'detached HEAD'. Puedes revisar por aquí, hacer
cambios experimentales y hacer commits, y puedes descartar cualquier
commit que hayas hecho en este estado sin impactar a tu rama realizando
otro checkout.

Si quieres crear una nueva rama para mantener los commits que has creado,
puedes hacerlo (ahora o después) usando -c con el comando checkout. Ejemplo:

  git switch -c <nombre-de-nueva-rama>

O deshacer la operación con:

  git switch -

Desactiva este aviso poniendo la variable de config advice.detachedHead en false

HEAD está ahora en d8a3bff4f 52280: update git completion for new options in git through to version 2.42.0


<br>
<font size="4">  
    <span style="color: blue;"><b>EJERCICIO 1 </b><br> 
    </span>
</font>  

- Haz un listado recursivo que muestre todos los ficheros y directorios (sin mostrar los que están ocultos) que hay dentro del directorio `zsh`, a cualquier profundidad, redirigiendo la salida al fichero `allfiles_zsh`.

In [11]:
#VII.1
ls -R zsh > allfiles_zsh

- Muestra las primeras 10 líneas del fichero `allfiles_zsh`.

In [12]:
#VII.2
head allfiles_zsh

zsh:
aclocal.m4
aczsh.m4
ChangeLog
Completion
Config
config.guess
config.sub
configure.ac
Doc


- Muestra las últimas 30 líneas del fichero `allfiles_zsh`.

In [13]:
head -n 30 allfiles_zsh

zsh:
aclocal.m4
aczsh.m4
ChangeLog
Completion
Config
config.guess
config.sub
configure.ac
Doc
Etc
FEATURES
Functions
INSTALL
install-sh
LICENCE
MACHINES
Makefile.in
Misc
mkinstalldirs
NEWS
README
Scripts
Src
StartupFiles
Test
Util

zsh/Completion:
AIX


- Verás que para cada subdirectorio cuyo contenido aparece listado, se muestra el nombre del directorio acabado por el carácter `:`. Vuelve a hacer el listado recursivo de `zsh` del ejercicio inicial, pero esta vez combínalo con el comando `grep` mediante una tubería para mostrar únicamente los nombres de los directorios (acabados en `:`).

In [14]:
#VII.4
ls -R zsh | grep ":$"

zsh:
zsh/Completion:
zsh/Completion/AIX:
zsh/Completion/AIX/Command:
zsh/Completion/AIX/Type:
zsh/Completion/Base:
zsh/Completion/Base/Completer:
zsh/Completion/Base/Core:
zsh/Completion/Base/Utility:
zsh/Completion/Base/Widget:
zsh/Completion/BSD:
zsh/Completion/BSD/Command:
zsh/Completion/BSD/Type:
zsh/Completion/Cygwin:
zsh/Completion/Cygwin/Command:
zsh/Completion/Darwin:
zsh/Completion/Darwin/Command:
zsh/Completion/Darwin/Type:
zsh/Completion/Debian:
zsh/Completion/Debian/Command:
zsh/Completion/Debian/Type:
zsh/Completion/Linux:
zsh/Completion/Linux/Command:
zsh/Completion/Linux/Type:
zsh/Completion/Mandriva:
zsh/Completion/Mandriva/Command:
zsh/Completion/openSUSE:
zsh/Completion/openSUSE/Command:
zsh/Completion/Redhat:
zsh/Completion/Redhat/Command:
zsh/Completion/Solaris:
zsh/Completion/Solaris/Command:
zsh/Completion/Solaris/Type:
zsh/Completion/Unix:
zsh/Completion/Unix/Command:
zsh/Completion/Unix/Type:
zsh/Completion/X:
zsh/Completion/X/Command:
zsh/Completion/X/Type:
zsh

- Extiende el comando anterior con una nueva tubería para quedarte con los nombres de los directorios sin el `:` final (*PISTA: puedes usar `tr` con la opción adecuada para eliminar un carácter o bien `cut`*). 

In [15]:
ls -R zsh | grep ":$" | cut -d ':' -f 1

zsh
zsh/Completion
zsh/Completion/AIX
zsh/Completion/AIX/Command
zsh/Completion/AIX/Type
zsh/Completion/Base
zsh/Completion/Base/Completer
zsh/Completion/Base/Core
zsh/Completion/Base/Utility
zsh/Completion/Base/Widget
zsh/Completion/BSD
zsh/Completion/BSD/Command
zsh/Completion/BSD/Type
zsh/Completion/Cygwin
zsh/Completion/Cygwin/Command
zsh/Completion/Darwin
zsh/Completion/Darwin/Command
zsh/Completion/Darwin/Type
zsh/Completion/Debian
zsh/Completion/Debian/Command
zsh/Completion/Debian/Type
zsh/Completion/Linux
zsh/Completion/Linux/Command
zsh/Completion/Linux/Type
zsh/Completion/Mandriva
zsh/Completion/Mandriva/Command
zsh/Completion/openSUSE
zsh/Completion/openSUSE/Command
zsh/Completion/Redhat
zsh/Completion/Redhat/Command
zsh/Completion/Solaris
zsh/Completion/Solaris/Command
zsh/Completion/Solaris/Type
zsh/Completion/Unix
zsh/Completion/Unix/Command
zsh/Completion/Unix/Type
zsh/Completion/X
zsh/Completion/X/Command
zsh/Completion/X/Type
zsh/Completion/X/Utility
zsh/Completion/Zs

- Extiende el comando anterior con una nueva tubería para contar cuántos directorios hay dentro de `zsh`. El resultado debería ser 75.

In [16]:
ls -R zsh | grep ":$" | cut -d ':' -f 1 | wc -l

75


- En realidad hay 74 directorios dentro de `zsh` ya que se incluye al propio directorio "base" `zsh`. Modifica el comando anterior para mostrar la primera línea y confirmar que se trata de `zsh`.

In [17]:
ls -R zsh | grep ":$" | cut -d ':' -f 1 | head -n 1

zsh


- Modifica el comando anterior para usar `grep` y mostrar las líneas **NO** contengan (opción `-v`) únicamente la cadena `zsh`. *PISTA: Recuerda que `^` y `$` representan el inicio y final de una línea en el patrón pasado a `grep`.*

In [18]:
ls -R zsh | grep ":$" | cut -d ':' -f 1 | grep -v "^zsh$"

zsh/Completion
zsh/Completion/AIX
zsh/Completion/AIX/Command
zsh/Completion/AIX/Type
zsh/Completion/Base
zsh/Completion/Base/Completer
zsh/Completion/Base/Core
zsh/Completion/Base/Utility
zsh/Completion/Base/Widget
zsh/Completion/BSD
zsh/Completion/BSD/Command
zsh/Completion/BSD/Type
zsh/Completion/Cygwin
zsh/Completion/Cygwin/Command
zsh/Completion/Darwin
zsh/Completion/Darwin/Command
zsh/Completion/Darwin/Type
zsh/Completion/Debian
zsh/Completion/Debian/Command
zsh/Completion/Debian/Type
zsh/Completion/Linux
zsh/Completion/Linux/Command
zsh/Completion/Linux/Type
zsh/Completion/Mandriva
zsh/Completion/Mandriva/Command
zsh/Completion/openSUSE
zsh/Completion/openSUSE/Command
zsh/Completion/Redhat
zsh/Completion/Redhat/Command
zsh/Completion/Solaris
zsh/Completion/Solaris/Command
zsh/Completion/Solaris/Type
zsh/Completion/Unix
zsh/Completion/Unix/Command
zsh/Completion/Unix/Type
zsh/Completion/X
zsh/Completion/X/Command
zsh/Completion/X/Type
zsh/Completion/X/Utility
zsh/Completion/Zsh
zs

- Finalmente, extiende el comando anterior para contar el número de líneas resultante mediante `wc`.

In [19]:
ls -R zsh | grep ":$" | cut -d ':' -f 1 | grep -v "^zsh$" | wc -l

74


El resultado es que *aparentemente* hay 74 directorios en `zsh`.

- Ahora vamos a utilizar el comando `find`, combinado con `wc` mediante una tubería, para comprobar que el número de directorios que obtenemos de esta otra forma coincide con el que hemos calculado antes mediante un `ls` recursivo.

In [20]:
#VII.10
find zsh -type d | wc -l

92


- Verás que, si cuentas directamente los directorios encontrados por `find`, el número resultante (92) no coincide con el esperado (74). Ejecuta `find` de nuevo sin conectar su salida a ninguna tubería para averiguar qué directorios está encontrando que no se listaban en el listado recursivo que hicimos con `ls`.

In [21]:
#VII.11
find zsh -type d

zsh
zsh/Etc
zsh/StartupFiles
zsh/Functions
zsh/Functions/Calendar
zsh/Functions/Prompts
zsh/Functions/Zftp
zsh/Functions/Exceptions
zsh/Functions/Example
zsh/Functions/Zle
zsh/Functions/Misc
zsh/Functions/VCS_Info
zsh/Functions/VCS_Info/Backends
zsh/Functions/Chpwd
zsh/Functions/Compctl
zsh/Functions/Newuser
zsh/Functions/MIME
zsh/Functions/TCP
zsh/Functions/Math
zsh/Misc
zsh/Doc
zsh/Doc/Zsh
zsh/Doc/help
zsh/Completion
zsh/Completion/Darwin
zsh/Completion/Darwin/Type
zsh/Completion/Darwin/Command
zsh/Completion/Unix
zsh/Completion/Unix/Type
zsh/Completion/Unix/Command
zsh/Completion/Zsh
zsh/Completion/Zsh/Type
zsh/Completion/Zsh/Function
zsh/Completion/Zsh/Context
zsh/Completion/Zsh/Command
zsh/Completion/openSUSE
zsh/Completion/openSUSE/Command
zsh/Completion/Solaris
zsh/Completion/Solaris/Type
zsh/Completion/Solaris/Command
zsh/Completion/Redhat
zsh/Completion/Redhat/Command
zsh/Completion/Base
zsh/Completion/Base/Utility
zsh/Completion/Base/Completer
zsh/Completion/Base/Widget
zsh/C

- Encuentra con `find` los directorios ocultos que hay en `zsh`. Verás que el único directorio oculto es `.git`.

In [22]:
find zsh -type d -name ".*"

zsh/.git


- Utiliza de nuevo `find` pero a su salida usa `grep` para quedarte que con las líneas que no contengan la cadena `.git` ni tampoco únicamente la cadena `zsh`, antes de contarlas con `wc`. **OJO**: En el patrón que pasamos a `grep`, el carácter punto `.` tiene un significado especial (equivale a un carácter cualquiera) por lo que debes anteponer la contrabarra `\` para quitarle su significado especial: `"\.git"`

In [23]:
#VII.13
find zsh -type d | grep -v "\.git" | grep -v "^zsh$" | wc -l

74


El resultado del comando anterior filtrando la salida de `find` debería ser 74, al igual que obtuvimos antes con `ls`. Es decir, los directorios que hay en `zsh`, excluyendo los que son ocultos o cuelgan de directorios ocultos.

- Ahora vamos a confirmar que el número de directorios que hemos contado coincide con lo que obtenemos haciendo un listado largo (`-l`) y recursivo (`-R`) de `zsh`. Sabiendo cómo se distinguen los directorios de los ficheros regulares en un listado largo (carácter que indica el tipo de fichero al comienzo de la línea), filtra la salida para quedarte únicamente con las que corresponden a directorios, y cuéntalas. (*Recuerda: `^` representa el inicio de línea en el patrón pasado a `grep`*)

In [24]:
#VII.14
ls -lR zsh | grep "^d" | wc -l

74


El resultado del comando anterior debería ser 74, ya que en el listado largo no se incluye al propio directorio *base* `zsh` (que sí se incluía tanto en la salida de `find` como en la del `ls` recursivo *corto* anterior).

- Cuenta los ficheros regulares que hay en `zsh`, que no sean ocultos ni cuelguen en directorios ocultos. Para ello, combina `find` para buscar, `grep` para descartar las líneas que correspondan a rutas de ficheros/directorios ocultos (o sea, rutas que contengan una barra `/` seguida de un punto, patrón  `"/\."`) y luego `wc` para contarlas. El resultado del comando debería ser 1618. 

In [25]:
#VII.15
find zsh -type f | grep -v "/\." | wc -l

1618


<br>
<font size="4">  
    <span style="color: blue;"><b>EJERCICIO 2 </b><br> 
    </span>
</font>  

- Con la opción `-printf "%s;%p;%M;%u;%g\n"`, utiliza `find` para generar un fichero llamado `source_code.csv` que contenga, para todos los ficheros regulares del directorio `zsh/Src` cuyo tamaño sea mayor que 50KiB, su tamaño, nombre, permisos, usuario y grupo, separados por punto y coma.

In [26]:
#VII.16
find zsh/Src -type f -size +50k -printf "%s;%p;%M;%u;%g\n" > source_code.csv

- Muestra el contenido del fichero generado anteriormente.

In [27]:
#VII.17
cat source_code.csv

176388;zsh/Src/utils.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
76620;zsh/Src/jobs.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
90506;zsh/Src/hist.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
98758;zsh/Src/glob.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
83826;zsh/Src/Modules/zftp.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
55980;zsh/Src/Modules/parameter.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
55131;zsh/Src/prompt.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
131362;zsh/Src/Zle/computil.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
90406;zsh/Src/Zle/compcore.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
74074;zsh/Src/Zle/compmatch.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
99091;zsh/Src/Zle/compctl.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
69631;zsh/Src/Zle/zle_refresh.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
86449;zsh/Src/Zle/complist.c;-rw-r--r--;jupyter-BR3dMjRh4o;jupyter-BR3dMjRh4o
59194;zsh/Src

- Extiende el comando anterior con una tubería y `sed` para sustituir la subcadena con el nombre del grupo que aparece al final (`$`) de cada línea, de forma que pase a a ser `developers` en vez de tu usuario. *PISTA: Se puede acceder a una variable de entorno en el comando `sed` con ${VARIABLE}*.

In [28]:
cat source_code.csv | sed "s/;${USER}$/;developers/"

176388;zsh/Src/utils.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
76620;zsh/Src/jobs.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
90506;zsh/Src/hist.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
98758;zsh/Src/glob.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
83826;zsh/Src/Modules/zftp.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
55980;zsh/Src/Modules/parameter.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
55131;zsh/Src/prompt.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
131362;zsh/Src/Zle/computil.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
90406;zsh/Src/Zle/compcore.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
74074;zsh/Src/Zle/compmatch.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
99091;zsh/Src/Zle/compctl.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
69631;zsh/Src/Zle/zle_refresh.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
86449;zsh/Src/Zle/complist.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
59194;zsh/Src/Zle/compresult.c;-rw-r--r--;jupyter-BR3dMjRh4o;developers
56459;zsh/Src/Zle/zle_main.c;-rw-r--r--;jupyt

- Extiende el comando anterior con otra tubería para sustituir la subcadena con el nombre del propietario (tu usuario) que aparece encerrado entre puntos y coma, de forma que pase a ser `steve` en vez del usuario correspondiente. 

In [38]:
cat source_code.csv | sed "s/;${USER}$/;developers/" | sed "s/;jupyter-BR3dMjRh4o;/;steve;/"

176388;zsh/Src/utils.c;-rw-r--r--;steve;developers
76620;zsh/Src/jobs.c;-rw-r--r--;steve;developers
90506;zsh/Src/hist.c;-rw-r--r--;steve;developers
98758;zsh/Src/glob.c;-rw-r--r--;steve;developers
83826;zsh/Src/Modules/zftp.c;-rw-r--r--;steve;developers
55980;zsh/Src/Modules/parameter.c;-rw-r--r--;steve;developers
55131;zsh/Src/prompt.c;-rw-r--r--;steve;developers
131362;zsh/Src/Zle/computil.c;-rw-r--r--;steve;developers
90406;zsh/Src/Zle/compcore.c;-rw-r--r--;steve;developers
74074;zsh/Src/Zle/compmatch.c;-rw-r--r--;steve;developers
99091;zsh/Src/Zle/compctl.c;-rw-r--r--;steve;developers
69631;zsh/Src/Zle/zle_refresh.c;-rw-r--r--;steve;developers
86449;zsh/Src/Zle/complist.c;-rw-r--r--;steve;developers
59194;zsh/Src/Zle/compresult.c;-rw-r--r--;steve;developers
56459;zsh/Src/Zle/zle_main.c;-rw-r--r--;steve;developers
76656;zsh/Src/Zle/zle_tricky.c;-rw-r--r--;steve;developers
90174;zsh/Src/parse.c;-rw-r--r--;steve;developers
171675;zsh/Src/exec.c;-rw-r--r--;steve;developers
202144;zsh/

- Extiende el comando anterior con dos tuberías para filtrar y mostrar únicamente las líneas que contienen las letras `b`, `g` o `k`, ordenadas numéricamente (*consulta `man sort` para buscar la opción adecuada*). Finalmente, redirige la salida del comando entubado completo a un fichero llamado `files_steve.csv`.

In [39]:
cat source_code.csv | sed "s/;${USER}$/;developers/" | sed "s/;jupyter-BR3dMjRh4o;/;steve;/" | grep '[bgk]' | sort -t ';' -k 1n > files_steve.csv

- Muestra el contenido del fichero `files_steve.csv`.

In [40]:
#VII.21
cat files_steve.csv

76620;zsh/Src/jobs.c;-rw-r--r--;steve;developers
76656;zsh/Src/Zle/zle_tricky.c;-rw-r--r--;steve;developers
98758;zsh/Src/glob.c;-rw-r--r--;steve;developers
125467;zsh/Src/subst.c;-rw-r--r--;steve;developers
202144;zsh/Src/builtin.c;-rw-r--r--;steve;developers


SALIDA:
```
76620;zsh/Src/jobs.c;-rw-rw-r--;steve;developers
76656;zsh/Src/Zle/zle_tricky.c;-rw-rw-r--;steve;developers
98758;zsh/Src/glob.c;-rw-rw-r--;steve;developers
125467;zsh/Src/subst.c;-rw-rw-r--;steve;developers
202144;zsh/Src/builtin.c;-rw-rw-r--;steve;developers
```

- Modifica el comando anterior para crear otro fichero llamado `files_tom.csv` que contenga una lista de los ficheros de `source_code.csv` donde el propietario sea `tom` en vez de tu usuario, y cuyo nombre **NO** contiene las letras `b`, `g` ni `k`.

In [46]:
cat source_code.csv | sed "s/;${USER}$/;developers/" | sed "s/;jupyter-BR3dMjRh4o;/;tom;/" | grep -v '[bgk]' | sort -t ';' -k1,1n > files_tom.csv

- Muestra el fichero `files_tom.csv` ordenado numéricamente de forma creciente.

In [47]:
cat files_tom.csv

55131;zsh/Src/prompt.c;-rw-r--r--;tom;developers
55980;zsh/Src/Modules/parameter.c;-rw-r--r--;tom;developers
56459;zsh/Src/Zle/zle_main.c;-rw-r--r--;tom;developers
59194;zsh/Src/Zle/compresult.c;-rw-r--r--;tom;developers
69631;zsh/Src/Zle/zle_refresh.c;-rw-r--r--;tom;developers
74074;zsh/Src/Zle/compmatch.c;-rw-r--r--;tom;developers
83594;zsh/Src/module.c;-rw-r--r--;tom;developers
83826;zsh/Src/Modules/zftp.c;-rw-r--r--;tom;developers
86449;zsh/Src/Zle/complist.c;-rw-r--r--;tom;developers
90174;zsh/Src/parse.c;-rw-r--r--;tom;developers
90406;zsh/Src/Zle/compcore.c;-rw-r--r--;tom;developers
90506;zsh/Src/hist.c;-rw-r--r--;tom;developers
99091;zsh/Src/Zle/compctl.c;-rw-r--r--;tom;developers
102320;zsh/Src/zsh.h;-rw-r--r--;tom;developers
119853;zsh/Src/pattern.c;-rw-r--r--;tom;developers
131362;zsh/Src/Zle/computil.c;-rw-r--r--;tom;developers
156661;zsh/Src/params.c;-rw-r--r--;tom;developers
171675;zsh/Src/exec.c;-rw-r--r--;tom;developers
176388;zsh/Src/utils.c;-rw-r--r--;tom;developers


SALIDA:
```
55131;zsh/Src/prompt.c;-rw-rw-r--;tom;developers
55980;zsh/Src/Modules/parameter.c;-rw-rw-r--;tom;developers
56459;zsh/Src/Zle/zle_main.c;-rw-rw-r--;tom;developers
59194;zsh/Src/Zle/compresult.c;-rw-rw-r--;tom;developers
69631;zsh/Src/Zle/zle_refresh.c;-rw-rw-r--;tom;developers
74074;zsh/Src/Zle/compmatch.c;-rw-rw-r--;tom;developers
83594;zsh/Src/module.c;-rw-rw-r--;tom;developers
83826;zsh/Src/Modules/zftp.c;-rw-rw-r--;tom;developers
86449;zsh/Src/Zle/complist.c;-rw-rw-r--;tom;developers
90174;zsh/Src/parse.c;-rw-rw-r--;tom;developers
90406;zsh/Src/Zle/compcore.c;-rw-rw-r--;tom;developers
90506;zsh/Src/hist.c;-rw-rw-r--;tom;developers
99091;zsh/Src/Zle/compctl.c;-rw-rw-r--;tom;developers
102320;zsh/Src/zsh.h;-rw-rw-r--;tom;developers
119853;zsh/Src/pattern.c;-rw-rw-r--;tom;developers
131362;zsh/Src/Zle/computil.c;-rw-rw-r--;tom;developers
156661;zsh/Src/params.c;-rw-rw-r--;tom;developers
171675;zsh/Src/exec.c;-rw-rw-r--;tom;developers
176388;zsh/Src/utils.c;-rw-rw-r--;tom;developers
```

- Concatena (`cat`) el contenido de los ficheros `csv` del directorio actual cuyo nombre contenga la cadena `tom` o `steve`, y genera un nuevo fichero llamado `source_code_developers.csv`.

In [48]:
cat *tom*.csv *steve*.csv > source_code_developers.csv

- Cuenta las líneas de los ficheros `csv` en el directorio actual, cuyo nombre empiece por la cadena `source`. Comprueba que ambos ficheros, original y transformado, tienen 24 líneas.

In [50]:
grep -h -c '' source*.csv

24
24


- Escribe un comando entubado que usando los datos de `source_code_developers.csv`, muestre el propietario del fichero de tamaño más pequeño. (*PISTA: Usa `cut` con su opción `-d` para indicar delimitador a usar, y con `-f` puedes indicar los campos a seleccionar; haz  `man cut` para más detalles. El punto y coma tiene un significado especial para el shell y por tanto debes entrecomillarlo*).

In [51]:
cat source_code_developers.csv | cut -d ';' -f 1,5 | sort -t ';' -n -k 1 | head -n 1 | cut -d ';' -f 2

developers


SALIDA:
```
tom
```

- Escribe un comando entubado que usando los datos de `source_code_developers.csv`, muestre el nombre y el propietario de los dos ficheros de tamaño mayor (*PISTA: a `cut` le puedes pasar un rango `n-m` o una lista `n,m` de campos a seleccionar*).

In [52]:
cat source_code_developers.csv | cut -d ';' -f 2,5 | sort -t ';' -n -k 1,1 | tail -n 2

zsh/Src/Zle/zle_tricky.c;developers
zsh/Src/zsh.h;developers


SALIDA:
```
zsh/Src/utils.c;tom
zsh/Src/builtin.c;steve
```

- Modifica el comando anterior para mostrar el nombre y tamaño de los dos ficheros de mayor tamaño cuyo propietario sea `steve`.

In [55]:
cat source_code_developers.csv | grep ";steve;" | cut -d ';' -f 2,1 | sort -t ';' -n -k 2,2 | tail -n 2

76656;zsh/Src/Zle/zle_tricky.c
98758;zsh/Src/glob.c


SALIDA:
```
125467;zsh/Src/subst.c
202144;zsh/Src/builtin.c
```

<br>
<font size="4">  
    <span style="color: blue;"><b>EJERCICIO 3 </b><br> 
    </span>
</font> 

- Utilizando los datos del fichero `source_code.csv` como entrada, utiliza `cut` para seleccionar únicamente el campo correspondiente al tamaño y luego ordena numéricamente el resultado en orden decreciente.

In [6]:
cut -d ';' -f 1 source_code.csv | sort -nr

202144
176388
171675
156661
131362
125467
119853
102320
99091
98758
90506
90406
90174
86449
83826
83594
76656
76620
74074
69631
59194
56459
55980
55131


- Extiende el comando anterior para mostrar únicamente el valor máximo del tamaño. El resultado debería ser 202144

In [7]:
cut -d ';' -f 1 source_code.csv | sort -nr | head -n 1

202144


- Modifica el comando anterior para quedarte con el nombre de los tres ficheros de mayor tamaño. El resultado debería ser:
```
zsh/Src/exec.c
zsh/Src/utils.c
zsh/Src/builtin.c
```

In [13]:
cut -d ';' -f 1,2 source_code.csv | sort -nr | cut -d ';' -f 2 | head -n 3

zsh/Src/builtin.c
zsh/Src/utils.c
zsh/Src/exec.c


- Combina mediante un *subshell* el comando anterior con `wc`, para mostrar el número de líneas, palabras y caracteres que contienen los tres ficheros de mayor tamaño de lo que aparecen en `source_code.csv`. El resultado debería ser:
```
  6451  23861 171675 zsh/Src/exec.c
  7721  27570 176388 zsh/Src/utils.c
  7583  28197 202144 zsh/Src/builtin.c
 21755  79628 550207 total
```

- Extiende el comando anterior para quedarte con el número de palabras que contiene cada uno de los tres ficheros (sin el total). *PISTA: Debes agrupar caracteres idénticos consecutivos con `tr -s` (*squeeze*) antes de separar por campos con `cut`.*

SALIDA:
```
23861
27570
28197
```

- Extiende el comando anterior con `paste` y `bc` para calcular la suma del número de palabras contenidas en los tres fichero de mayor tamaño. El resultado debería ser 79628 (el correspondiente al total en el comando anterior).

<br>
<font size="4">  
    <span style="color: blue;"><b>EJERCICIO 4 - Filtrado y subshells </b><br> 
    </span>
</font>  

- Busca en los ficheros regulares del directorio `zsh`, que no cuelguen del directorio `.git`, y muestra aquellas líneas contengan un *shebang* (cadena `#!/bin/sh`).

SALIDA:
```
zsh/Src/mkmakemod.sh:#!/bin/sh
zsh/Etc/FAQ.yo:    #!/bin/sh
zsh/Test/E01options.ztst:  print "#!/bin/sh\necho File in upper dir" >pathtestdir/findme
zsh/Test/E01options.ztst:  print "#!/bin/sh\necho File in lower dir" >pdt_topdir/pathtestdir/findme
zsh/Test/list-XFails:#!/bin/sh
zsh/Test/A01grammar.ztst:  print "#!/bin/sh\necho Found the script." >test_path_script/myscript
zsh/Functions/Misc/harden:#!/bin/sh
zsh/install-sh:#!/bin/sh
zsh/Config/installfns.sh:#!/bin/sh
zsh/Config/uninstallfns.sh:#!/bin/sh
```

- Extiende el comando anterior con un filtro adicional para mostrar únicamente las ocurrencias de dicha cadena en la primera línea de cada fichero. *PISTA: Debes pasarle a `grep` la opción adecuada para que muestre el número de cada línea concordante, y luego filtrar por la cadena adecuada.*

SALIDA:
```
zsh/Src/mkmakemod.sh:1:#!/bin/sh
zsh/Test/list-XFails:1:#!/bin/sh
zsh/Functions/Misc/harden:1:#!/bin/sh
zsh/install-sh:1:#!/bin/sh
zsh/Config/installfns.sh:1:#!/bin/sh
zsh/Config/uninstallfns.sh:1:#!/bin/sh
```

- Extiende el comando anterior con un filtro adicional para quedarte únicamente con el nombre de los ficheros que contienen un *shebang* en la primera línea:

SALIDA:
```
zsh/Src/mkmakemod.sh
zsh/Test/list-XFails
zsh/Functions/Misc/harden
zsh/install-sh
zsh/Config/installfns.sh
zsh/Config/uninstallfns.sh
```

- Extiende el comando anterior con un *subshell* para hacer un listado largo de dichos ficheros (que muestre los detalles de los ficheros regulares que no cuelguen de `.git` y que contienen un *shebang* en la primera línea):

SALIDA:
```
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o  1754 nov 13 08:40 zsh/Config/installfns.sh
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o  1445 nov 13 08:40 zsh/Config/uninstallfns.sh
-rw-rw-r-- 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o    96 nov 13 08:40 zsh/Functions/Misc/harden
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o 13184 nov 13 08:40 zsh/install-sh
-rw-rw-r-- 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o 15446 nov 13 08:40 zsh/Src/mkmakemod.sh
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o   209 nov 13 08:40 zsh/Test/list-XFails
```

- Extiende el comando anterior para evitar mostrar los ficheros que no son ejecutables por cualquier usuario de la máquina.

SALIDA:
```
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o  1754 nov 10 07:37 zsh/Config/installfns.sh
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o  1445 nov 10 07:37 zsh/Config/uninstallfns.sh
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o 13184 nov 10 07:37 zsh/install-sh
-rwxrwxr-x 1 jupyter-BR3dMjRh4o jupyter-BR3dMjRh4o   209 nov 10 07:37 zsh/Test/list-XFails
```

- Extiende el comando anterior para quedarte con el último campo del listado largo (nombres de los ficheros regulares ejecutables que no cuelgan de `.git` y que contienen un *shebang* `#!/bin/sh` en la primera línea):

SALIDA:
```
zsh/Config/installfns.sh
zsh/Config/uninstallfns.sh
zsh/install-sh
zsh/Test/list-XFails
```

- Extiende el comando anterior con un nuevo *subshell* para mostrar las dos primeras líneas de dichos ficheros (ficheros regulares ejecutables que no cuelgan de .git y que contienen un shebang en la primera línea).

SALIDA:
```
==> zsh/Config/installfns.sh <==
#!/bin/sh

fndir=$DESTDIR$fndir

==> zsh/Config/uninstallfns.sh <==
#!/bin/sh

fndir=$DESTDIR$fndir

==> zsh/install-sh <==
#!/bin/sh
# install - install a program, script, or datafile


==> zsh/Test/list-XFails <==
#!/bin/sh
# This script lists tests that are currently expected to fail.  (I.e., tests
# for bugs that haven't been fixed yet.)
```

**FIN DEL CUADERNO** (*no borres esta celda*)

@@@@ practica7b-tuberias-ejercicios.ipynb @@@@